[project]
name = "her-dl"
version = "0.1.0"
description = "Human Emotion Recognition Deep Learning Project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask",
    "keras",
    "matplotlib",
    "numpy",
    "opencv-python-headless",
    "pillow",
    "scikit-learn",
    "seaborn",
    "tensorboard",
    "tensorflow-rocm",
]
